variable vpc_cidr_block {}
variable subnet_cidr_block {}
variable region {}
variable env_prefix {}
variable zone_id {}
variable shared_credentials_file {}
variable profile {}
variable public_key_location {}
variable instance_type {}
variable image_name_regex {}