---
- name: Install node and npm
  hosts: xxx.xxx.xxx.xxx
  tasks:
    - name: Update apt repo and cache
      ansible.builtin.apt:
        - update_cache: yes
        - force_apt_get: yes
        - cache_valid_time: 3600
    - name: Install nodejs and npm
      ansible.builtin.apt:
        pkg:
          - nodejs
          - npm

- name: Deploy nodejs app
  hosts: xxx.xxx.xxx.xxx
  tasks:
    - name: Copy nodejs folder to the server
      ansible.builtin.copy:
        src:
        dest: /root/app-1.0.0.tgz
    - name: Unpack the nodejs file
      ansible.builtin.unarchive:
        src: /root/app-1.0.0.tgz
        dest: /root/
        remote_src: yes 
    - name: Install nodejs
      community.general.npm:
         path: /root/package
    - name: Start the application
      ansible.builtin.command:
        chdir: /root/package/app
        cmd: node server
      async: 1000
      poll: 0
    - name: Ensure app is running
      ansible.builtin.shell: ps aux | grep node
      register: app_status
    - ansible.builtin.debug: msg={{app_status.stdout_lines}}
